### ISSUE TITLE
Google Code difference?

### ISSUE THREAD

**Issue by davidhuser** [benoitguigal/python-epson-printer#15]
What's the difference of your repo with the repo on [google code?](https://code.google.com/p/python-escpos/)

**Comment by benoitguigal** [comment]
This project is based on python-escpos hosted on google code. The main difference is the support for printing images as described by Nicholas Piasecki. http://nicholas.piasecki.name/blog/2009/12/sending-a-bit-image-to-an-epson-tm-t88iii-receipt-printer-using-c-and-escpos/.
