### ISSUE TITLE
Accents encoding ?

### ISSUE THREAD

**Issue by lorrisbaum** [benoitguigal/python-epson-printer#28]
Hello, I am a French student and for a project I try to print tickets with content with accents "é à è" ... But they are replaced by strange characters on the tickets. Do you have an idea how to fix it?

Thank you.

**Comment by benoitguigal** [comment]
Hi @lorrisbaum,
As I understand it, Python string are encoded as unicode whereas the printer only understands extended ASCII [http://www.asciitable.com/](http://www.asciitable.com/). You may try preprocessing your strings with this function:

```
EXTENDED_ASCII_TABLE = {
    u'Ç': 128,
    U'É': 144,
    ... # define all the extended ASCII characters you will need here
}

def string_to_extended_ascii(my_string):
    return [ord(c) if ord(c) < 127 else EXTENDED_ASCII_TABLE[c] for c in my_string]
```

and then you can use it like this:
```
my_string = u'Le français ÇÉ bien'
extended_ascii_array =  string_to_extended_ascii(my_string)
printer.write_bytes(extended_ascii_array)
```

**Comment by lorrisbaum** [comment]
Perfect!!! It works like a charm. Thank's :)
